apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-fbg-server
  name: {{ .Release.Name }}-fbg-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: {{ .Release.Name }}-fbg-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
