apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas.web }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
      - env:
        - name: SERVER_TYPE
          value: WEB
        - name: FBG_BACKEND_TARGET
          value: http://{{ .Release.Name }}-fbg-server
        - name: NEXT_PUBLIC_I18N_ENABLED
          value: 'true'
        image: {{ .Values.images.web }} 
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: {{ .Release.Name }}-web
        resources:
          limits:
            cpu: "1" 
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
status: {}
